#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenTecSP.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlmacenTecSP")]
	public partial class ArticuloDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertArticulo(Articulo instance);
    partial void UpdateArticulo(Articulo instance);
    partial void DeleteArticulo(Articulo instance);
    #endregion
		
		public ArticuloDataContext() : 
				base(global::AlmacenTecSP.Properties.Settings.Default.AlmacenTecSPConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ArticuloDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArticuloDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArticuloDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArticuloDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Articulo> Articulos
		{
			get
			{
				return this.GetTable<Articulo>();
			}
		}
        public IEnumerable<Articulo> GetAllCustomers()
        {
            var items = this.Articulos.Select(item => item).OrderBy(item => item.nombre);

            return items;
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Articulo")]
	public partial class Articulo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idArt;
		
		private string _nombre;
		
		private int _cantidad_;
		
		private string _unidad;
		
		private string _codigo;
		
		private System.DateTime _fechEntrada;
		
		private System.Nullable<int> _canntMinima;
		
		private bool _locacion;
		
		private int _idCategoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidArtChanging(int value);
    partial void OnidArtChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Oncantidad_Changing(int value);
    partial void Oncantidad_Changed();
    partial void OnunidadChanging(string value);
    partial void OnunidadChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnfechEntradaChanging(System.DateTime value);
    partial void OnfechEntradaChanged();
    partial void OncanntMinimaChanging(System.Nullable<int> value);
    partial void OncanntMinimaChanged();
    partial void OnlocacionChanging(bool value);
    partial void OnlocacionChanged();
    partial void OnidCategoriaChanging(int value);
    partial void OnidCategoriaChanged();
    #endregion
		
		public Articulo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idArt
		{
			get
			{
				return this._idArt;
			}
			set
			{
				if ((this._idArt != value))
				{
					this.OnidArtChanging(value);
					this.SendPropertyChanging();
					this._idArt = value;
					this.SendPropertyChanged("idArt");
					this.OnidArtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[cantidad ]", Storage="_cantidad_", DbType="Int NOT NULL")]
		public int cantidad_
		{
			get
			{
				return this._cantidad_;
			}
			set
			{
				if ((this._cantidad_ != value))
				{
					this.Oncantidad_Changing(value);
					this.SendPropertyChanging();
					this._cantidad_ = value;
					this.SendPropertyChanged("cantidad_");
					this.Oncantidad_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidad", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string unidad
		{
			get
			{
				return this._unidad;
			}
			set
			{
				if ((this._unidad != value))
				{
					this.OnunidadChanging(value);
					this.SendPropertyChanging();
					this._unidad = value;
					this.SendPropertyChanged("unidad");
					this.OnunidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(15)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechEntrada", DbType="DateTime NOT NULL")]
		public System.DateTime fechEntrada
		{
			get
			{
				return this._fechEntrada;
			}
			set
			{
				if ((this._fechEntrada != value))
				{
					this.OnfechEntradaChanging(value);
					this.SendPropertyChanging();
					this._fechEntrada = value;
					this.SendPropertyChanged("fechEntrada");
					this.OnfechEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canntMinima", DbType="Int")]
		public System.Nullable<int> canntMinima
		{
			get
			{
				return this._canntMinima;
			}
			set
			{
				if ((this._canntMinima != value))
				{
					this.OncanntMinimaChanging(value);
					this.SendPropertyChanging();
					this._canntMinima = value;
					this.SendPropertyChanged("canntMinima");
					this.OncanntMinimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locacion", DbType="Bit NOT NULL")]
		public bool locacion
		{
			get
			{
				return this._locacion;
			}
			set
			{
				if ((this._locacion != value))
				{
					this.OnlocacionChanging(value);
					this.SendPropertyChanging();
					this._locacion = value;
					this.SendPropertyChanged("locacion");
					this.OnlocacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
