<?xml version="1.0" encoding="utf-8"?><Database Name="AlmacenTecSP" Class="EntregablesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BD\AlmacenTecSP.mdf;Integrated Security=True" SettingsObjectName="AlmacenTecSP.Properties.Settings" SettingsPropertyName="AlmacenTecSPConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Entregables" Member="Entregables">
    <Type Name="Entregable">
      <Column Name="idEntrg" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCateg" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>