#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenTecSP.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlmacenTecSP")]
	public partial class SalidaArticuloDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSalidaArticulo(SalidaArticulo instance);
    partial void UpdateSalidaArticulo(SalidaArticulo instance);
    partial void DeleteSalidaArticulo(SalidaArticulo instance);
    #endregion
		
		public SalidaArticuloDataContext() : 
				base(global::AlmacenTecSP.Properties.Settings.Default.AlmacenTecSPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SalidaArticuloDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SalidaArticuloDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SalidaArticuloDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SalidaArticuloDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SalidaArticulo> SalidaArticulos
		{
			get
			{
				return this.GetTable<SalidaArticulo>();
			}
		}
        public IEnumerable<SalidaArticulo> GetAllCustomers()
        {
            var items = this.SalidaArticulos.Select(item => item).OrderBy(item => item.idArt);

            return items;
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SalidaArticulo")]
	public partial class SalidaArticulo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idSaArt;
		
		private int _idSolicitud;
		
		private int _idArt;
		
		private int _cantidad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSaArtChanging(int value);
    partial void OnidSaArtChanged();
    partial void OnidSolicitudChanging(int value);
    partial void OnidSolicitudChanged();
    partial void OnidArtChanging(int value);
    partial void OnidArtChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    #endregion
		
		public SalidaArticulo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSaArt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idSaArt
		{
			get
			{
				return this._idSaArt;
			}
			set
			{
				if ((this._idSaArt != value))
				{
					this.OnidSaArtChanging(value);
					this.SendPropertyChanging();
					this._idSaArt = value;
					this.SendPropertyChanged("idSaArt");
					this.OnidSaArtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSolicitud", DbType="Int NOT NULL")]
		public int idSolicitud
		{
			get
			{
				return this._idSolicitud;
			}
			set
			{
				if ((this._idSolicitud != value))
				{
					this.OnidSolicitudChanging(value);
					this.SendPropertyChanging();
					this._idSolicitud = value;
					this.SendPropertyChanged("idSolicitud");
					this.OnidSolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArt", DbType="Int NOT NULL")]
		public int idArt
		{
			get
			{
				return this._idArt;
			}
			set
			{
				if ((this._idArt != value))
				{
					this.OnidArtChanging(value);
					this.SendPropertyChanging();
					this._idArt = value;
					this.SendPropertyChanged("idArt");
					this.OnidArtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
